# Generated by Django 5.1.3 on 2025-05-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('under', '0004_stockrequest_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrequest',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
