# Generated by Django 5.1.3 on 2025-05-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('under', '0005_stockrequest_approved_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrequest',
            name='is_viewed_by_maker',
            field=models.BooleanField(default=False),
        ),
    ]
