# Generated by Django 5.1.3 on 2025-05-24 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('under', '0006_stockrequest_is_viewed_by_maker'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockin',
            name='stock_added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stockin_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
