# Generated by Django 5.1.3 on 2025-05-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('under', '0007_stockin_stock_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrequest',
            name='request_id',
            field=models.CharField(blank=True, editable=False, max_length=12, unique=True),
        ),
    ]
