# Generated by Django 5.1.3 on 2025-05-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('under', '0008_stockrequest_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrequest',
            name='request_id',
            field=models.CharField(blank=True, editable=False, max_length=36, unique=True),
        ),
    ]
